language: rust

rust:
  - nightly-2018-10-14

cache: cargo

addons:
  apt:
    packages:
      - yamllint

install:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview

script:
  - find . -name *.yml -exec yamllint {} \;
  - cargo test
  - cargo fmt -- --check
  - cargo clippy
  - cargo package

notifications:
  email:
    - robert@resin.io
    - cyryl@resin.io
  on_success: change
  on_failure: always
