[package]
name = "balena-configuration-dsl"
version = "0.2.5"
authors = ["Robert Vojta <robert@balena.io>", "Cyryl Płotnicki <cyryl@balena.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
heck = "0.3"
regex = "1.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
yaml-merge-keys = {version= "0.3", features = ["serde_yaml"]}

balena-temen = "0.0.16"

[dev-dependencies]
pretty_assertions = "0.5"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen= { version="0.2", features = ["serde-serialize"] }
console_error_panic_hook = "0.1"

[target.wasm32-unknown-unknown.dev-dependencies]
wasm-bindgen-test = "0.2"

[lib]
crate-type = ["lib", "cdylib"]
