[package]
name = "balena-configuration-dsl"
version = "0.1.4"
authors = ["Robert Vojta <robert@balena.io>", "Cyryl Płotnicki <cyryl@balena.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7.5" # needs to be the same version as the one used by `yaml-merge-keys` -
# emailed the maintainers if they could release the update of the dependencies
yaml-merge-keys = {version= "0.2.1", features = ["serde_yaml"]}
heck = "0.3"
regex = "1.0"

[dev-dependencies]
pretty_assertions = "0.5"


