[package]
name = "balena_configuration_dsl"
version = "0.1.4"
authors = ["Robert Vojta <robert@balena.io>", "Cyryl Płotnicki <cyryl@balena.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
heck = "0.3"
regex = "1.0"

[dev-dependencies]
pretty_assertions = "0.5"


